Small documentation PR
Parallel-in-Time/pySDC pull request #357
Opened 2023-09-20 11:39 UTC by lisawim

I finished the documentation for the rest of the problem classes. The Allen-Cahn classes' docu should now inlcude the correct description of which boundary conditions are used, because I took a look into each AC implementation.

Further, I documented all the FEniCS and PETSc classes. For FEniCS, there is a very detailed tutorial which I read and I was able to give a more detailed documentation for the classes using FEniCS. However, for PETSc it was very hard (for me!) to find references/websites/etc. to find where usage of PETSc is explained. So, I was not able for the classes using PETSc giving a detailed documentation. Probably this would be okay, because in `pySDC` there should not be a detailed documentation of what's going on in PETSc..

The `fenics_vortex_2d` class has also documentation but I am not sure if I could find out the correct equation implemented in the problem class, and I also could not find reasonable literature regarding that. I would really appreciate if you can give me feedback of what I need to still improve and/or change in the documentation, but of course only if you have the time.

I also would feel more comfortable if @brownbaerchen could add the equations to his `Quench` and `QuenchIMEX` class or could send to me s.t. I can add them, for completeness.

Then.. this PR should solve issue #286 completely and we are much closer to `v6` of `pySDC` I hope..

2023-09-20 12:07 UTC, brownbaerchen commented
Quench is a 1D toy version of the problem from Section 4.3 from [here](https://iopscience.iop.org/article/10.1088/1361-6668/acbeea) that was set up by Erik Schnaubelt.
The exploding magnet can be cited with [this report](https://cds.cern.ch/record/1168025?ln=en).

2023-09-20 12:17 UTC, lisawim commented
Thanks! I'll add that.

2023-09-20 12:17 UTC, brownbaerchen commented
Thanks a lot :)

2023-09-20 14:50 UTC, brownbaerchen requested changes
Well done, very thorough! I just glanced over most of the files and noticed a few minor things. I did not read any of the equations, though.

2023-09-20 14:50 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/HarmonicOscillator.py
> +    which is a second-order problem. The unknown function :math:`x` denotes the position of the mass, and their
`the` instead of `their`

2023-09-20 14:50 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/HeatEquation_1D_FEniCS_matrix_forced.py
> +    In this class the problem is implemented in the way that it is solved in space using FEniCS [1]_. Hence, the problem
This formulation is a bit convoluted. Maybe `The spatial part is solved using FEniCS`?

2023-09-20 14:50 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/HeatEquation_1D_FEniCS_matrix_forced.py
> +    In this class the problem is implemented in the way that it is solved in space using FEniCS [1]_. Hence, the problem
Same same

2023-09-20 14:50 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/HeatEquation_1D_FEniCS_weak_forced.py
> +    In this class the problem is implemented in the way that it is solved in space using FEniCS [1]_. Hence, the problem
Same, same

2023-09-20 14:50 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/VorticityVelocity_2D_FEniCS_periodic.py
> +    The nonlinear system is solved in an *fully-implicit* way using Dolfin's weak solver.
a instead of an

2023-09-20 14:50 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/generic_ND_FD.py
> +    Example implementing the N-dimensional linear equation
Base class for finite difference spatial discretisation in N-dimensions

2023-09-20 14:50 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/generic_ND_FD.py
> +    where :math:`A  \in \mathbb{R}^{n \times n}` is a finite difference matrix arising from spatial discretization.
where :math:`A \in \mathbb{R}^{nN \times nN} is a matrix arising from finite difference discretisation of spatial derivatives with n degrees of freedom per dimension and N dimensions.

2023-09-20 14:50 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/generic_ND_FD.py
> +        Order of the derivative used for finite difference discretization.
Order of the spatial derivative

2023-09-20 14:50 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/generic_ND_FD.py
> +        Order of the finite difference discretization.
Order of accuracy of the finite difference discretization

2023-09-20 15:13 UTC, lisawim commented
I appreciate your effort very much! Thanks a lot! I'll change that immediately. Now I have something to do during my waiting time for the train to Kiel. :D

2023-09-21 08:01 UTC, pancetta commented
@brownbaerchen Accept?

2023-09-21 08:23 UTC, brownbaerchen reviewed
I only glanced over this very quickly and have tiny and unimportant comments. We can merge now, if you want.

2023-09-21 08:23 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/AllenCahn_1D_FD.py
> +    *semi-implicit* way, i.e., the Laplacian is treated implicitly by solving the linear system including the
maybe you can remove the "by solving the linear system including the Laplacian here

2023-09-21 08:23 UTC, brownbaerchen commented on pySDC/implementations/problem_classes/AllenCahn_1D_FD.py
> +    For time-stepping, this problem will be treated in a *fully-implicit* way the nonlinear system is solved using Newton.
Full stop between "way" and "the"

2023-09-21 10:06 UTC, brownbaerchen approved these changes

2023-09-21 10:11 UTC, merged